import type { Locale } from "@/i18n/routing";
import { type Experience, experienceSchema } from "./schema";

const experiences = {
  en: [
    {
      company: "Click Planos",
      role: "Senior Fullstack Engineer",
      location: "Brasília, Brazil",
      start: "2025-07",
      end: null,
      highlights: [
        "Led the refactor and delivery of a new product architecture by decoupling a monolithic Next.js application into a scalable frontend (Next.js) and backend (NestJS). Delivered the project in 32 days (ahead of a 40-day deadline), increasing user interactions by 40% and boosting conversion rate by 4%, while supporting a platform handling thousands of daily user registrations.",
        "Optimized application performance and data flow by implementing caching strategies and scalable backend services, improving system responsiveness and handling increased traffic. Leveraged Redis for caching, PostgreSQL for data persistence, and Drizzle ORM for type-safe database access and migrations, alongside AWS services including S3, EC2, RDS, and Lambda.",
        "Designed and implemented third-party integrations with platforms such as D4Sign, HubSpot, Pipedrive, and PostHog, enabling seamless contract signing, CRM automation, and user behavior analytics. Improved data consistency and reduced manual operational effort through robust API integrations using Node.js, Nest.js, TypeScript, and RESTful services.",
        "Built serverless data processing pipelines using AWS Lambda integrated with Golang middleware to handle CRM data ingestion, improving request performance by ~5% and ensuring data integrity across systems. Utilized AWS Lambda, Golang, HubSpot API, and Pipedrive API.",
        "Enhanced development workflow and team productivity in a small team environment by implementing CI/CD pipelines and AI-assisted development practices. Introduced GitHub Actions, Doppler for secrets management, and AI tools like CodeRabbit and Cursor (Claude), accelerating delivery cycles and improving code quality, increasing development speed by 30% and reducing bugs and issues by 20%.",
      ],
      stack: [
        "Next.js",
        "NestJS",
        "TypeScript",
        "TanStack Query",
        "Zod",
        "Zustand",
        "Drizzle ORM",
        "PostgreSQL",
        "Redis",
        "AWS",
        "Vercel",
        "PostHog",
        "Golang",
      ],
    },
    {
      company: "Evernow",
      role: "Senior DevSecOps Analyst",
      location: "São Paulo, Brazil",
      start: "2022-09",
      end: null,
      highlights: [
        "Implemented and maintained secure development pipelines for leading healthcare and financial institutions, integrating SAST, SCA, and DAST tools into CI/CD workflows. Standardized vulnerability scanning across applications, increasing security coverage and reducing exposure to critical risks. Strengthened security posture for millions of users and ensured enterprise-grade compliance through orchestration of Fortify, Veracode, and Debricked.",
        "Designed reusable YAML templates in Azure DevOps to enforce secure pipeline standards and prevent vulnerability scan bypass, particularly for Fortify integrations. Accelerated pipeline adoption and reduced manual configuration while ensuring compliance with security policies. Leveraged Azure DevOps YAML templates, Terraform, and Infrastructure as Code (IaC) practices.",
        "Led large-scale vulnerability remediation initiative, identifying and fixing hundreds of SQL Injection issues across ~300 applications of a healthcare platform. Enhanced security for systems serving millions of users by leveraging automated scan reports and AI-assisted workflows. Used Veracode, SonarQube, VS Code, GitHub Copilot, and Python-based Fortify API integrations.",
        "Acted in high-pressure war room operations for a major financial client, improving AppSec support efficiency and contract performance over a 6-month critical period. Increased response speed by 40%, handled 5,567 tickets, and analyzed over 20,000 vulnerabilities, including 6,328 false positives, ensuring mitigation aligned with OWASP Top 10 (2021). Utilized GitHub Actions, Veracode, SonarQube, and ServiceNow.",
        "Redesigned vulnerability observability and incident response workflows, implementing automated reporting pipelines integrated with monitoring and ticketing systems. Reduced first response SLA from 3 days to 24 hours and decreased ticket volume by 30% through automation and root-cause analysis. Used AWS CloudWatch, ServiceNow, Python, Devin, and StackSpot.",
      ],
      stack: [
        "Python",
        "GitHub Actions",
        "AWS CloudWatch",
        "Fortify",
        "Veracode",
        "SonarQube",
        "OWASP",
        "Azure DevOps",
      ],
    },
    {
      company: "Fridom",
      role: "Senior Fullstack Engineer",
      location: "Brasília, Brazil",
      start: "2020-01",
      end: "2025-01",
      highlights: [
        "Led internationalization and large-scale refactor for a platform with 1M+ users, restructuring 2 mobile apps, 3 Node.js APIs, and an admin dashboard to support 4 languages (PT-BR/PT, EN, ES, FR). Built a dynamic translation system enabling real-time updates, reducing support tickets by 30% and enabling expansion into Europe and the US, generating new revenue. Utilized React Native, React.js, Node.js, PostgreSQL, and i18n.",
        "Diagnosed and resolved a critical financial bug in a high-traffic payment system, identifying an infinite loop via log tracing in AWS EC2 (PM2). Reduced API response time from 5 minutes to 10 seconds and corrected inconsistencies, resulting in a financial impact exceeding R$50K and improving reliability. Used Node.js, AWS EC2, PM2, and log analysis.",
        "Engineered a real-time mobile platform for event discovery and transactions, supporting hundreds of thousands of users and high volumes. Implemented geolocation, WebSockets for real-time payments, and QR code validation for ticketing and delivery. Ensured secure transactions using JWT and role-based access control. Utilized React Native (Expo), Node.js, WebSockets, PostgreSQL, and Zoop.",
        "Mitigated a high-scale DDoS/brute-force attack on a credit card endpoint by redesigning API security, sanitizing inputs, and migrating from Node.js to NestJS for improved validation. Reduced API response time by 12% and prevented further attacks. Leveraged NestJS, Node.js, and secure coding practices.",
        "Led recovery of a high-risk agricultural platform contract, acting as Technical Lead to realign delivery and client expectations through Agile workflows. Translated needs into epics and tasks in Jira, improving delivery quality. Prevented a R$600K penalty and drove an additional R$120K investment. Utilized Python, Django, JavaScript, HTML, CSS, and Jira.",
      ],
      stack: [
        "React",
        "Next.js",
        "React Native",
        "Expo",
        "Node.js",
        "NestJS",
        "WebSockets",
        "PostgreSQL",
        "AWS EC2",
        "Zoop",
        "Jira",
        "Python",
        "Django",
        "PHP",
        "i18n",
      ],
    },
    {
      company: "Fest Intermediação e Tecnologia",
      role: "Fullstack Engineer",
      location: "Brasília, Brazil",
      start: "2023-11",
      end: "2024-11",
      highlights: [
        "Designed and developed a ticketing dashboard using Next.js, enabling real-time ticket sales, payments, and QR code generation. Integrated WebSockets for live transaction updates and built financial analytics dashboards for revenue tracking. Supported a platform processing thousands in weekly transactions.",
        "Led backend refactor from Node.js to NestJS, improving API structure, maintainability, and security. Implemented Swagger for API documentation and standardized endpoint architecture, resulting in a 4% reduction in response time and better developer experience. Utilized NestJS, Node.js, TypeScript, and Swagger.",
        "Implemented payment infrastructure from scratch by integrating Asaas APIs into the platform, enabling secure and scalable financial transactions. Enhanced payment reliability and supported real-time processing aligned with business growth.",
        "Built a unified data-driven system leveraging a shared PostgreSQL database across services, ensuring consistency of users, partners, and financial data. Enabled seamless integration between dashboard, backend, and existing platform, improving data integrity and operational visibility. Utilized PostgreSQL and backend integration patterns.",
      ],
      stack: [
        "Next.js",
        "React",
        "Node.js",
        "NestJS",
        "WebSockets",
        "OAuth",
        "PostgreSQL",
        "Asaas API",
      ],
    },
  ],
  "pt-BR": [
    {
      company: "Click Planos",
      role: "Engenheiro Fullstack Sênior",
      location: "Brasília, Brasil",
      start: "2025-07",
      end: null,
      highlights: [
        "Liderou a refatoração e entrega de uma nova arquitetura de produto desacoplando um monolito Next.js em um frontend escalável (Next.js) e um backend (NestJS). Entregou o projeto 32 dias (20% antes do prazo de 40 dias), aumentando as interações dos usuários em 40% e a taxa de conversão em 4%, enquanto prestava suporte e manutenção a uma plataforma que atende milhares de cadastros diários de usuários.",
        "Otimizou o desempenho da aplicação e o fluxo de dados implementando estratégias de caching e serviços de backend escaláveis, melhorando a responsividade do sistema e lidando com o aumento de tráfego.",
        "Projetou e implementou integrações com plataformas terceiras como D4Sign, HubSpot, Pipedrive, e PostHog, permitindo a assinatura de contratos e termos digitais, automação de CRM e análise de comportamento do usuário de forma transparente. Melhorou a consistência dos dados e reduziu o esforço operacional manual por meio de integrações robustas com APIs REST usando Node.js, Nest.js, TypeScript, e serviços RESTful.",
        "Construiu pipelines de processamento de dados serverless usando AWS Lambda integrado com middleware em Golang para lidar com a ingestão de dados do CRM, melhorando o desempenho das requisições em ~5% e garantindo a integridade dos dados em todo o sistema.",
        "Aprimorou o fluxo de desenvolvimento e a produtividade da equipe em um ambiente de equipe pequena implementando pipelines de CI/CD e práticas de desenvolvimento assistido por IA. Introduziu GitHub Actions, Doppler para gerenciamento de segredos, e ferramentas de IA como CodeRabbit e Cursor (Claude), acelerando os ciclos de entrega e melhorando a qualidade do código, aumentando a velocidade de desenvolvimento em 30% e reduzindo bugs e problemas em 20%.",
      ],
      stack: [
        "Next.js",
        "NestJS",
        "TypeScript",
        "TanStack Query",
        "Zod",
        "Zustand",
        "Drizzle ORM",
        "PostgreSQL",
        "Redis",
        "AWS",
        "PostHog",
      ],
    },
    {
      company: "Evernow",
      role: "Analista DevSecOps Sênior",
      location: "São Paulo, Brasil",
      start: "2022-09",
      end: null,
      highlights: [
        "Implementação e manutenção em pipelines de desenvolvimento seguro para instituições líderes na área da saúde e financeira, integrando ferramentas SAST, SCA e DAST em fluxos de CI/CD. Padronizou a identificação de vulnerabilidades em todas as aplicações, aumentando a cobertura de segurança e reduzindo o risco de exposição a vulnerabilidades críticas. Fortaleceu a maturidade de segurança para milhões de usuários e garantiu conformidade empresarial por meio da orquestração de Fortify, Veracode e Debricked.",
        "Projetou e implementou templates YAML reutilizáveis no Azure DevOps para padronizar pipelines de segurança evitando bypass dos scans de identificação de vulnerabilidades, particularmente para integrações do Fortify. Acelerou a implementação de pipelines e reduziu a configuração manual enquanto garantia conformidade com políticas de segurança.",
        "Liderou uma iniciativa de mitigação de vulnerabilidades em larga escala, identificando e corrigindo centenas de vulnerabilidades de injeção SQL em cerca de 300 aplicações de uma plataforma de saúde. Aumentou a segurança de sistemas que atendem milhões de usuários por meio de relatórios de verificação automatizados e fluxos de trabalho assistidos por IA.",
        "Atuação em operações de WarRoom de alta pressão para um grande cliente do ramo financeiro, melhorando a eficiência do suporte de segurança e o desempenho da equipe em um período crítico de 6 meses. Aumentou a velocidade de resposta em 40%, lidou com 5.567 chamados e analisou mais de 20.000 vulnerabilidades, incluindo 6.328 falsos positivos, garantindo que a mitigação esteja alinhada com o OWASP Top 10 (2021).",
        "Redesenhou as workflows de observabilidade e resposta a incidentes, implementando pipelines de relatórios automatizados integrados com sistemas de monitoramento e sistema de chamados. Reduziu o SLA de resposta de primeira resposta de 3 dias para 24 horas e o volume de chamados em 30% por meio de automação e análise de causa raiz.",
      ],
      stack: [
        "Python",
        "GitHub Actions",
        "AWS CloudWatch",
        "Fortify",
        "Veracode",
        "SonarQube",
        "OWASP",
        "Azure DevOps",
      ],
    },
    {
      company: "Fridom",
      role: "Engenheiro Fullstack Sênior",
      location: "Brasília, Brasil",
      start: "2020-01",
      end: "2025-01",
      highlights: [
        "Liderou a internacionalização e a refatoração em larga escala de uma plataforma com 1M+ usuários, reestruturando 2 aplicativos móveis, 3 APIs Node.js, e um painel administrativo para suportar 4 idiomas (PT-BR/PT, EN, ES, FR). Construiu um sistema de tradução dinâmico que permite atualizações em tempo real, reduzindo os chamados de suporte em 30% e viabilizando a expansão para Europa e Estados Unidos, gerando novo receita.",
        "Liderou a recuperação de um contrato de plataforma de restauração ambiental de alto risco, atuando como Líder Técnico para realinhar a entrega e as expectativas do cliente por meio de fluxos de trabalho ágeis. Traduziu necessidades em epicos e tarefas no Jira, melhorando a qualidade da entrega. Evitou uma multa de R$600K e impulsionou um investimento adicional de R$120K.",
        "Diagnosticou e resolveu um bug crítico sistema de alto tráfego de transações financeiras, identificando um loop infinito via rastreamento de logs na AWS EC2 (PM2). Reduziu o tempo de resposta da API de 5 minutos para 10 segundos e corrigiu inconsistências, resultando em um impacto financeiro superior a R$50K e melhorando a confiabilidade.",
        "Desenvolveu uma plataforma mobile com eventos em tempo real para descoberta de shows e transações financeiras, suportando centenas de milhares de usuários e volumes altos. Implementou geolocalização, WebSockets para pagamentos em tempo real, e validação de QR code para bilheteria e entrega de produtos. Garantiu transações seguras usando JWT e controle de acesso baseado em papéis.",
        "Mitigou um ataque de DDoS/força bruta em larga escala em um endpoint de cartão de crédito redesenhando a segurança da API, sanitizando entradas e migrando de Node.js para NestJS para melhoria de validação. Reduziu o tempo de resposta da API em 12% e impediu ataques adicionais.",
      ],
      stack: [
        "React",
        "React.js",
        "React Native",
        "Expo",
        "Node.js",
        "NestJS",
        "WebSockets",
        "PostgreSQL",
        "AWS EC2",
        "Zoop",
        "Jira",
        "Python",
        "Django",
        "PHP",
        "i18n",
      ],
    },
    {
      company: "Fest Intermediação e Tecnologia",
      role: "Engenheiro Fullstack",
      location: "Brasília, Brasil",
      start: "2023-11",
      end: "2024-11",
      highlights: [
        "Projetou e desenvolveu um painel de bilheteria usando Next.js, permitindo vendas de ingressos em tempo real, pagamentos e geração de QR code. Integrou WebSockets para atualizações em tempo real de transações e construiu dashboards de análise financeira para rastreamento de receita. Prestou manutenção em uma plataforma que processa milhares de transações semanais.",
        "Liderou a refatoração do backend de Node.js para NestJS, melhorando a estrutura da API, a manutenibilidade e a segurança. Implementou Swagger para documentação da API e padronizou a arquitetura de endpoints, resultando em uma redução de 4% no tempo de resposta e uma melhor experiência de desenvolvedor.",
        "Implementou uma infraestrutura de pagamentos do zero integrando APIs Asaas na plataforma, permitindo transações financeiras seguras e escaláveis. Aumentou a confiabilidade dos pagamentos e suportou o processamento em tempo real alinhado com o crescimento do negócio.",
        "Construiu um sistema de dados unificado aproveitando um banco de dados PostgreSQL compartilhado entre serviços, garantindo consistência de dados de usuários, parceiros e dados financeiros. Permitiu integração perfeita entre painel, backend e plataforma existente, melhorando a integridade dos dados e a visibilidade operacional.",
      ],
      stack: [
        "Next.js",
        "React",
        "Node.js",
        "NestJS",
        "WebSockets",
        "OAuth",
        "PostgreSQL",
        "Asaas API",
      ],
    },
  ],
} satisfies Record<Locale, unknown[]>;

const experienceByLocale = {
  en: experiences.en.map((entry) => experienceSchema.parse(entry)),
  "pt-BR": experiences["pt-BR"].map((entry) => experienceSchema.parse(entry)),
} satisfies Record<Locale, Experience[]>;

export function getExperience(locale: Locale): Experience[] {
  return experienceByLocale[locale];
}
