import { experienceSchema } from "./schema";

export const experience = [
  {
    company: "Click Planos",
    role: "Senior Fullstack Engineer",
    location: "Brasília, Brazil",
    start: "2025-07",
    end: null,
    highlights: [
      "Decoupled a monolithic Next.js application into a scalable frontend (Next.js) and backend (NestJS); delivered 20% ahead of a 40-day deadline, boosting user interactions 40% and conversion 4% on a platform handling thousands of daily registrations.",
      "Architected cloud-native backend services with Redis caching, PostgreSQL persistence and Drizzle ORM on AWS (S3, EC2, RDS, Lambda), applying performance tuning to sustain higher traffic volumes.",
      "Shipped third-party integrations with D4Sign, HubSpot, Pipedrive and PostHog for contract signing, CRM automation and product observability via RESTful APIs, eliminating manual operational effort.",
      "Accelerated delivery speed 30% and reduced production issues 20% by implementing CI/CD with GitHub Actions, Doppler-managed secrets and AI-assisted workflows (CodeRabbit, Cursor, Claude).",
    ],
    stack: [
      "Next.js",
      "NestJS",
      "TypeScript",
      "TanStack Query",
      "Zod",
      "Zustand",
      "Drizzle ORM",
      "PostgreSQL",
      "Redis",
      "AWS",
      "PostHog",
    ],
  },
  {
    company: "Evernow",
    role: "Senior DevSecOps Analyst",
    location: "São Paulo, Brazil",
    start: "2022-09",
    end: null,
    highlights: [
      "Architected secure CI/CD pipelines for healthcare and financial platforms serving millions of users, integrating SAST, SCA and DAST tooling (Fortify, Veracode, SonarQube) with GitHub Actions and AWS CloudWatch; cut first-response SLA from 3 days to 24 hours and ticket volume 30% through Python-based automation.",
      "Led code-level remediation of SQL Injection vulnerabilities across ~300 applications, building Python integrations with Fortify APIs to deliver OWASP Top 10–compliant code at scale.",
    ],
    stack: [
      "Python",
      "GitHub Actions",
      "AWS CloudWatch",
      "Fortify",
      "Veracode",
      "SonarQube",
    ],
  },
  {
    company: "Fridom",
    role: "Senior Fullstack Engineer",
    location: "Brasília, Brazil",
    start: "2020-01",
    end: "2025-01",
    highlights: [
      "Engineered a real-time mobile platform for event discovery and transactions with geolocation, WebSocket-based payments, QR code validation, JWT and role-based access control, serving hundreds of thousands of users.",
      "Diagnosed and resolved a critical payment bug via log tracing in AWS EC2 (PM2), reducing API response time from 5 minutes to 10 seconds and recovering over R$50K in financial discrepancies.",
      "Enhanced API security by redesigning endpoints and migrating from Node.js to NestJS, mitigating large-scale DDoS and brute-force attacks and reducing response time by 12%.",
    ],
    stack: [
      "React Native",
      "Expo",
      "Node.js",
      "NestJS",
      "WebSockets",
      "PostgreSQL",
      "AWS EC2",
      "Zoop",
    ],
  },
  {
    company: "Fest Intermediação e Tecnologia",
    role: "Fullstack Engineer",
    location: "Brasília, Brazil",
    start: "2023-11",
    end: "2024-11",
    highlights: [
      "Developed a real-time ticketing dashboard with Next.js and WebSockets, delivering live transaction updates, financial analytics and QR code generation; supported thousands of weekly transactions.",
      "Migrated the backend from Node.js to NestJS with Swagger-documented APIs, improving response time 4% and establishing a standardized, microservices-ready endpoint architecture.",
      "Implemented payment infrastructure from scratch by integrating Asaas APIs, enabling secure, real-time transactions aligned with business growth.",
    ],
    stack: [
      "Next.js",
      "React",
      "Node.js",
      "NestJS",
      "WebSockets",
      "PostgreSQL",
      "Asaas API",
    ],
  },
].map((entry) => experienceSchema.parse(entry));
