import type { Locale } from "@/i18n/routing";
import { type Experience, experienceSchema } from "./schema";

const experiences = {
  en: [
    {
      company: "Click Planos",
      role: "Senior Fullstack Engineer",
      location: "Brasília, Brazil",
      start: "2025-07",
      end: null,
      highlights: [
        "Led the refactor and delivery of a new product architecture by decoupling a monolithic Next.js application into a scalable frontend (Next.js) and backend (NestJS). Delivered the project in 32 days (ahead of a 40-day deadline), increasing user interactions by 40% and boosting conversion rate by 4%, while supporting a platform handling thousands of daily user registrations.",
        "Optimized application performance and data flow by implementing caching strategies and scalable backend services, improving system responsiveness and handling increased traffic. Leveraged Redis for caching, PostgreSQL for data persistence, and Drizzle ORM for type-safe database access and migrations, alongside AWS services including S3, EC2, RDS, and Lambda.",
        "Designed and implemented third-party integrations with platforms such as D4Sign, HubSpot, Pipedrive, and PostHog, enabling seamless contract signing, CRM automation, and user behavior analytics. Improved data consistency and reduced manual operational effort through robust API integrations using Node.js, Nest.js, TypeScript, and RESTful services.",
        "Built serverless data processing pipelines using AWS Lambda integrated with Golang middleware to handle CRM data ingestion, improving request performance by ~5% and ensuring data integrity across systems. Utilized AWS Lambda, Golang, HubSpot API, and Pipedrive API.",
        "Enhanced development workflow and team productivity in a small team environment by implementing CI/CD pipelines and AI-assisted development practices. Introduced GitHub Actions, Doppler for secrets management, and AI tools like CodeRabbit and Cursor (Claude), accelerating delivery cycles and improving code quality, increasing development speed by 30% and reducing bugs and issues by 20%.",
      ],
      stack: [
        "Next.js",
        "NestJS",
        "TypeScript",
        "TanStack Query",
        "Zod",
        "Zustand",
        "Drizzle ORM",
        "PostgreSQL",
        "Redis",
        "AWS",
        "PostHog",
        "Golang",
      ],
    },
    {
      company: "Evernow",
      role: "Senior DevSecOps Analyst",
      location: "São Paulo, Brazil",
      start: "2022-09",
      end: null,
      highlights: [
        "Implemented and maintained secure development pipelines for leading healthcare and financial institutions, integrating SAST, SCA, and DAST tools into CI/CD workflows. Standardized vulnerability scanning across applications, increasing security coverage and reducing exposure to critical risks. Strengthened security posture for millions of users and ensured enterprise-grade compliance through orchestration of Fortify, Veracode, and Debricked.",
        "Designed reusable YAML templates in Azure DevOps to enforce secure pipeline standards and prevent vulnerability scan bypass, particularly for Fortify integrations. Accelerated pipeline adoption and reduced manual configuration while ensuring compliance with security policies. Leveraged Azure DevOps YAML templates, Terraform, and Infrastructure as Code (IaC) practices.",
        "Led large-scale vulnerability remediation initiative, identifying and fixing hundreds of SQL Injection issues across ~300 applications of a healthcare platform. Enhanced security for systems serving millions of users by leveraging automated scan reports and AI-assisted workflows. Used Veracode, SonarQube, VS Code, GitHub Copilot, and Python-based Fortify API integrations.",
        "Acted in high-pressure war room operations for a major financial client, improving AppSec support efficiency and contract performance over a 6-month critical period. Increased response speed by 40%, handled 5,567 tickets, and analyzed over 20,000 vulnerabilities, including 6,328 false positives, ensuring mitigation aligned with OWASP Top 10 (2021). Utilized GitHub Actions, Veracode, SonarQube, and ServiceNow.",
        "Redesigned vulnerability observability and incident response workflows, implementing automated reporting pipelines integrated with monitoring and ticketing systems. Reduced first response SLA from 3 days to 24 hours and decreased ticket volume by 30% through automation and root-cause analysis. Used AWS CloudWatch, ServiceNow, Python, Devin, and StackSpot.",
      ],
      stack: [
        "Python",
        "GitHub Actions",
        "AWS CloudWatch",
        "Fortify",
        "Veracode",
        "SonarQube",
        "Azure DevOps",
      ],
    },
    {
      company: "Fridom",
      role: "Senior Fullstack Engineer",
      location: "Brasília, Brazil",
      start: "2020-01",
      end: "2025-01",
      highlights: [
        "Led internationalization and large-scale refactor for a platform with 1M+ users, restructuring 2 mobile apps, 3 Node.js APIs, and an admin dashboard to support 4 languages (PT-BR/PT, EN, ES, FR). Built a dynamic translation system enabling real-time updates, reducing support tickets by 30% and enabling expansion into Europe and the US, generating new revenue. Utilized React Native, React.js, Node.js, PostgreSQL, and i18n.",
        "Diagnosed and resolved a critical financial bug in a high-traffic payment system, identifying an infinite loop via log tracing in AWS EC2 (PM2). Reduced API response time from 5 minutes to 10 seconds and corrected inconsistencies, resulting in a financial impact exceeding R$50K and improving reliability. Used Node.js, AWS EC2, PM2, and log analysis.",
        "Engineered a real-time mobile platform for event discovery and transactions, supporting hundreds of thousands of users and high volumes. Implemented geolocation, WebSockets for real-time payments, and QR code validation for ticketing and delivery. Ensured secure transactions using JWT and role-based access control. Utilized React Native (Expo), Node.js, WebSockets, PostgreSQL, and Zoop.",
        "Mitigated a high-scale DDoS/brute-force attack on a credit card endpoint by redesigning API security, sanitizing inputs, and migrating from Node.js to NestJS for improved validation. Reduced API response time by 12% and prevented further attacks. Leveraged NestJS, Node.js, and secure coding practices.",
        "Led recovery of a high-risk agricultural platform contract, acting as Technical Lead to realign delivery and client expectations through Agile workflows. Translated needs into epics and tasks in Jira, improving delivery quality. Prevented a R$600K penalty and drove an additional R$120K investment. Utilized Python, Django, JavaScript, HTML, CSS, and Jira.",
      ],
      stack: [
        "React",
        "Next.js",
        "React Native",
        "Expo",
        "Node.js",
        "NestJS",
        "WebSockets",
        "PostgreSQL",
        "AWS EC2",
        "Zoop",
        "Jira",
        "Python",
        "Django",
        "PHP",
      ],
    },
    {
      company: "Fest Intermediação e Tecnologia",
      role: "Fullstack Engineer",
      location: "Brasília, Brazil",
      start: "2023-11",
      end: "2024-11",
      highlights: [
        "Developed a real-time ticketing dashboard with Next.js and WebSockets, delivering live transaction updates, financial analytics and QR code generation; supported thousands of weekly transactions.",
        "Migrated the backend from Node.js to NestJS with Swagger-documented APIs, improving response time 4% and establishing a standardized, microservices-ready endpoint architecture.",
        "Implemented payment infrastructure from scratch by integrating Asaas APIs, enabling secure, real-time transactions aligned with business growth.",
      ],
      stack: [
        "Next.js",
        "React",
        "Node.js",
        "NestJS",
        "WebSockets",
        "PostgreSQL",
        "Asaas API",
      ],
    },
  ],
  "pt-BR": [
    {
      company: "Click Planos",
      role: "Engenheiro Fullstack Sênior",
      location: "Brasília, Brasil",
      start: "2025-07",
      end: null,
      highlights: [
        "Liderou a refatoração e entrega de uma nova arquitetura de produto desacoplando um monolito Next.js em um frontend escalável (Next.js) e um backend (NestJS). Entregou o projeto em 32 dias (20% antes do prazo de 40 dias), aumentando as interações dos usuários em 40% e aumentando a taxa de conversão em 4%, enquanto suportava uma plataforma que atendia milhares de cadastros diários de usuários.",
        "Led the refactor and delivery of a new product architecture by decoupling a monolithic Next.js application into a scalable frontend (Next.js) and backend (NestJS). Delivered the project in 32 days (ahead of a 40-day deadline), increasing user interactions by 40% and boosting conversion rate by 4%, while supporting a platform handling thousands of daily user registrations.",
        "Optimized application performance and data flow by implementing caching strategies and scalable backend services, improving system responsiveness and handling increased traffic. Leveraged Redis for caching, PostgreSQL for data persistence, and Drizzle ORM for type-safe database access and migrations, alongside AWS services including S3, EC2, RDS, and Lambda.",
        "Designed and implemented third-party integrations with platforms such as D4Sign, HubSpot, Pipedrive, and PostHog, enabling seamless contract signing, CRM automation, and user behavior analytics. Improved data consistency and reduced manual operational effort through robust API integrations using Node.js, Nest.js, TypeScript, and RESTful services.",
        "Built serverless data processing pipelines using AWS Lambda integrated with Golang middleware to handle CRM data ingestion, improving request performance by ~5% and ensuring data integrity across systems. Utilized AWS Lambda, Golang, HubSpot API, and Pipedrive API.",
        "Enhanced development workflow and team productivity in a small team environment by implementing CI/CD pipelines and AI-assisted development practices. Introduced GitHub Actions, Doppler for secrets management, and AI tools like CodeRabbit and Cursor (Claude), accelerating delivery cycles and improving code quality, increasing development speed by 30% and reducing bugs and issues by 20%.",
      ],
      stack: [
        "Next.js",
        "NestJS",
        "TypeScript",
        "TanStack Query",
        "Zod",
        "Zustand",
        "Drizzle ORM",
        "PostgreSQL",
        "Redis",
        "AWS",
        "PostHog",
      ],
    },
    {
      company: "Evernow",
      role: "Analista DevSecOps Sênior",
      location: "São Paulo, Brasil",
      start: "2022-09",
      end: null,
      highlights: [
        "Arquitetou pipelines de CI/CD seguros para plataformas de saúde e financeiras que atendem milhões de usuários, integrando ferramentas SAST, SCA e DAST (Fortify, Veracode, SonarQube) com GitHub Actions e AWS CloudWatch; reduziu o SLA de primeira resposta de 3 dias para 24 horas e o volume de chamados em 30% por meio de automação em Python.",
        "Liderou a remediação, em nível de código, de vulnerabilidades de SQL Injection em cerca de 300 aplicações, construindo integrações em Python com as APIs do Fortify para entregar código em conformidade com o OWASP Top 10 em escala.",
      ],
      stack: [
        "Python",
        "GitHub Actions",
        "AWS CloudWatch",
        "Fortify",
        "Veracode",
        "SonarQube",
      ],
    },
    {
      company: "Fridom",
      role: "Engenheiro Fullstack Sênior",
      location: "Brasília, Brasil",
      start: "2020-01",
      end: "2025-01",
      highlights: [
        "Desenvolveu uma plataforma mobile em tempo real para descoberta de eventos e transações, com geolocalização, pagamentos via WebSocket, validação por QR code, JWT e controle de acesso por perfil, atendendo centenas de milhares de usuários.",
        "Diagnosticou e resolveu um bug crítico de pagamento via rastreamento de logs na AWS EC2 (PM2), reduzindo o tempo de resposta da API de 5 minutos para 10 segundos e recuperando mais de R$50 mil em divergências financeiras.",
        "Reforçou a segurança da API redesenhando endpoints e migrando de Node.js para NestJS, mitigando ataques de DDoS e força bruta em larga escala e reduzindo o tempo de resposta em 12%.",
      ],
      stack: [
        "React Native",
        "Expo",
        "Node.js",
        "NestJS",
        "WebSockets",
        "PostgreSQL",
        "AWS EC2",
        "Zoop",
      ],
    },
    {
      company: "Fest Intermediação e Tecnologia",
      role: "Engenheiro Fullstack",
      location: "Brasília, Brasil",
      start: "2023-11",
      end: "2024-11",
      highlights: [
        "Desenvolveu um dashboard de bilheteria em tempo real com Next.js e WebSockets, entregando atualizações de transações ao vivo, análises financeiras e geração de QR code; suportou milhares de transações semanais.",
        "Migrou o backend de Node.js para NestJS com APIs documentadas via Swagger, melhorando o tempo de resposta em 4% e estabelecendo uma arquitetura de endpoints padronizada e pronta para microsserviços.",
        "Implementou a infraestrutura de pagamentos do zero integrando as APIs da Asaas, viabilizando transações seguras e em tempo real alinhadas ao crescimento do negócio.",
      ],
      stack: [
        "Next.js",
        "React",
        "Node.js",
        "NestJS",
        "WebSockets",
        "PostgreSQL",
        "Asaas API",
      ],
    },
  ],
} satisfies Record<Locale, unknown[]>;

const experienceByLocale = {
  en: experiences.en.map((entry) => experienceSchema.parse(entry)),
  "pt-BR": experiences["pt-BR"].map((entry) => experienceSchema.parse(entry)),
} satisfies Record<Locale, Experience[]>;

export function getExperience(locale: Locale): Experience[] {
  return experienceByLocale[locale];
}
